// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateUser implements createUser operation.
//
// Create a user.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *User) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// Get all users.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}
