openapi: 3.1.0
info:
  title: auster-mono
  description: auster-mono
  contact: {}
  version: 1.0.0
servers:
    - url: http://localhost:3000
paths:
  '/users':
    get:
      operationId: getUsers
      summary: Get all users
      description: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: createUser
      summary: Create a user
      description: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
          $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - name
        - email
    Error:
        type: object
        properties:
            message:
              type: string
        required:
            - message